import React from 'react'
import { useNavigate } from 'react-router-dom'
import {
  FileText,
  Sparkles,
  ArrowRight,
  Download,
} from 'lucide-react'

export const ReportsPage: React.FC = () => {
  const navigate = useNavigate()

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-6 fade-in">
      {/* Header */}
      <div className="border-b border-[#E4E4E7] pb-5">
        <div className="flex items-center gap-2 text-xs font-medium text-zinc-800 mb-1">
          <span className="w-2 h-2 rounded-full bg-black"></span>
          Automated Technical Documentation
        </div>
        <h1 className="text-2xl font-bold text-zinc-900 tracking-tight flex items-center gap-2.5">
          <FileText className="w-6 h-6 text-zinc-900" />
          <span>Engineering Thermal Analysis Reports</span>
        </h1>
        <p className="text-sm text-zinc-600 mt-1">
          Automated publication-grade PDF documentation generated via ReportLab summarizing ANSYS simulation results.
        </p>
      </div>

      {/* Guide Card */}
      <div className="mono-card bg-white space-y-5 border border-[#E4E4E7] shadow-[0_1px_3px_rgba(0,0,0,0.05)]">
        <div className="flex items-center gap-2 text-xs font-semibold text-zinc-800 uppercase tracking-wider border-b border-[#E4E4E7] pb-3">
          <Sparkles size={15} className="text-zinc-900" />
          <span>Automated Engineering Report Structure</span>
        </div>
        <p className="text-xs text-zinc-600 leading-relaxed max-w-2xl">
          Reports generated by this platform adhere to Himalayan engineering and building physics documentation standards:
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 pt-1">
          {[
            { num: '01', title: 'Executive Summary', desc: 'Overview of geographical location, elevation, and simulation parameters.', color: 'text-zinc-900' },
            { num: '02', title: 'Recommended Configuration', desc: 'Optimal architecture & envelope assembly with multi-criteria weighted score.', color: 'text-zinc-800' },
            { num: '03', title: 'Comparison Matrix', desc: 'Quantitative evaluation across all tested shelter designs and envelope materials.', color: 'text-zinc-700' },
            { num: '04', title: 'Assumptions & Physics', desc: 'McAdams convection, radiation models, and ANSYS MAPDL v26.1 solver setup.', color: 'text-zinc-600' },
          ].map(s => (
            <div key={s.num} className="bg-[#F8FAFC] p-4 rounded-lg border border-[#E4E4E7] space-y-2 flex flex-col justify-between">
              <span className={`font-mono text-xl font-bold ${s.color}`}>
                {s.num}
              </span>
              <div>
                <span className="text-xs font-bold text-zinc-900 block mb-1">
                  {s.title}
                </span>
                <span className="text-[11px] text-zinc-500 block leading-relaxed">
                  {s.desc}
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Action Card */}
      <div className="mono-card bg-white p-8 text-center space-y-4 max-w-xl mx-auto my-6 border border-[#E4E4E7] shadow-[0_1px_3px_rgba(0,0,0,0.05)]">
        <div className="w-12 h-12 rounded-xl bg-zinc-100 border border-zinc-200 mx-auto flex items-center justify-center text-zinc-900">
          <Download size={22} />
        </div>
        <h2 className="text-lg font-bold text-zinc-900">Generate PDF from Active Results</h2>
        <p className="text-xs text-zinc-600 leading-relaxed max-w-md mx-auto">
          Comprehensive multi-page engineering reports can be generated and downloaded directly from the <strong>Results & Recommendations</strong> dashboard.
        </p>
        <button
          onClick={() => navigate('/recommendations')}
          className="btn btn-primary text-xs flex items-center gap-2 mx-auto"
        >
          <span>Go to Results & Recommendations</span>
          <ArrowRight size={14} />
        </button>
      </div>
    </div>
  )
}
