import React from 'react'
import { useNavigate } from 'react-router-dom'
import {
  FileText,
  Sparkles,
  ArrowRight,
  Download,
} from 'lucide-react'

export const ReportsPage: React.FC = () => {
  const navigate = useNavigate()

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-6 fade-in">
      {/* Header */}
      <div className="border-b border-[#1A1D24] pb-5">
        <div className="flex items-center gap-2 text-xs font-medium text-white mb-1">
          <span className="w-2 h-2 rounded-full bg-white"></span>
          Automated Technical Documentation
        </div>
        <h1 className="text-2xl font-bold text-white tracking-tight flex items-center gap-2.5">
          <FileText className="w-6 h-6 text-white" />
          <span>Engineering Thermal Analysis Reports</span>
        </h1>
        <p className="text-sm text-slate-400 mt-1">
          Automated publication-grade PDF documentation generated via ReportLab summarizing ANSYS simulation results.
        </p>
      </div>

      {/* Guide Card */}
      <div className="mono-card space-y-5">
        <div className="flex items-center gap-2 text-xs font-semibold text-slate-200 uppercase tracking-wider border-b border-[#1A1D24] pb-3">
          <Sparkles size={15} className="text-white" />
          <span>Automated Engineering Report Structure</span>
        </div>
        <p className="text-xs text-slate-300 leading-relaxed max-w-2xl">
          Reports generated by this platform adhere to Himalayan engineering and building physics documentation standards:
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 pt-1">
          {[
            { num: '01', title: 'Executive Summary', desc: 'Overview of geographical location, elevation, and simulation parameters.', color: 'text-white' },
            { num: '02', title: 'Recommended Configuration', desc: 'Optimal architecture & envelope assembly with multi-criteria weighted score.', color: 'text-white' },
            { num: '03', title: 'Comparison Matrix', desc: 'Quantitative evaluation across all tested shelter designs and envelope materials.', color: 'text-emerald-400' },
            { num: '04', title: 'Assumptions & Physics', desc: 'McAdams convection, radiation models, and ANSYS MAPDL v26.1 solver setup.', color: 'text-teal-400' },
          ].map(s => (
            <div key={s.num} className="bg-[#0D0F13] p-4 rounded-lg border border-[#1A1D24] space-y-2 flex flex-col justify-between">
              <span className={`font-mono text-xl font-bold ${s.color}`}>
                {s.num}
              </span>
              <div>
                <span className="text-xs font-bold text-white block mb-1">
                  {s.title}
                </span>
                <span className="text-[11px] text-slate-400 block leading-relaxed">
                  {s.desc}
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Action Card */}
      <div className="mono-card p-8 text-center space-y-4 max-w-xl mx-auto my-6 border border-[#20242C] bg-[#121418]">
        <div className="w-12 h-12 rounded-xl bg-white/10 border border-white/20 mx-auto flex items-center justify-center text-white">
          <Download size={22} />
        </div>
        <h2 className="text-lg font-bold text-white">Generate PDF from Active Results</h2>
        <p className="text-xs text-slate-300 leading-relaxed max-w-md mx-auto">
          Comprehensive multi-page engineering reports can be generated and downloaded directly from the <strong>Results & Recommendations</strong> dashboard.
        </p>
        <button
          onClick={() => navigate('/recommendations')}
          className="btn btn-primary text-xs flex items-center gap-2 mx-auto"
        >
          <span>Go to Results & Recommendations</span>
          <ArrowRight size={14} />
        </button>
      </div>
    </div>
  )
}
